origin_resource = "subscription"

[[create_resource]]
resource_type = "dns"
relation_type = "BASELINE_TEMPLATE"
name = "public-dns"
[create_resource.properties]
function = "resolver"
zones = ["domain.com"]
description = "A public DNS zone configuration defines an administrative namespace that a single entity manages, containing resource records that map public domain names to IP addresses."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"

[[create_resource]]
resource_type = "dns"
relation_type = "BASELINE_TEMPLATE"
name = "private-dns"
[create_resource.properties]
function = "resolver"
zones = ["sandbox.my.salesforce.com"]
description = "A private DNS zone configuration defines an administrative namespace that a single entity manages, containing resource records that map internal domain names to IP addresses."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"
