origin_resource = "router"

filters = { "json!" = "firewall-rules.json" }

segments = { "template!" = '''
{%- set count = origin_resource.network | length -%}
{%- set range = origin_resource.cidr -%}
{{- range | cidr_split_n(n=count) | join(sep=',') -}}
''' }

[[create_resource]]
create_from = { property = "network" }
relation_type = "DEPENDS_ON"
name = "{{- origin_resource.provider.name | lower -}}-{{- origin_resource.location[0].code | lower -}}-{{- property.value | lower -}}-network"
[create_resource.properties]
function = "{{- origin_resource.function -}}"
cidr = "{{- segments[property.index] -}}"
subnet = ["a", "b"]
gateway = ["sf"]
filter = ["{{- filters['unrestricted-tcp-egress'] -}}", "{{- filters['dns-udp-ingress'] -}}", "{{- filters['dns-tcp-ingress'] -}}"]
description = "The {{ origin_resource.function }} network is an virtual, on-demand infrastructure that connects users and applications to computing resources like servers, storage, and software, all delivered over the internet."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"
