origin_resource = "login"

provider_name = { "function!" = "{{- origin_resource.name | regexp(expr='s/^([^-]+)-.*/\\1/') | lower -}}" }
resource_id = { "json!" = "dictionary.json", jmespath = "values(@)[?name == provider_name ] | [0]" }

[[create_resource]]
create_from = { property = "permission" }
relation_type = "DERIVED_FROM"
name = "{{ origin_resource.name | regexp(expr='s/^([^-]+-[^-]+)-.*/\\1/') | lower }}-{{ property.value | lower }}-permission"
[create_resource.properties]
function = "allow"
description = "tbd"
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"

# "eks:DescribeCluster","eks:ListClusters","eks:AccessKubernetesApi"

#origin_resource = "role"

#[[link_resources]]
#with = "permission"
#join = { local = "service", remote = "service" }
#create_relation = { type = "DEPENDS_ON" }
