origin_resource = "service"

[[create_resource]]
resource_type = "role"
relation_type = "DEFINED_BY"
name = "{{- origin_resource.name | lower -}}-administrator"
[create_resource.properties]
function = "{{- origin_resource.function | lower -}}"
permission = ["create", "read", "update", "delete"]
description = "The role describes the permissions of a {{ origin_resource.function }} service administrator."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"
