origin_resource = "resident"

provider = { "json!" = "provider.json", jmespath = "values(@)[?name == 'AWS' ] | [0]" }

[[create_resource]]
resource_type = "subscription"
relation_type = "DEFINED_BY"
name = "{{- origin_resource.name | lower -}}-{{- subscription | lower -}}"
[create_resource.properties]
home = "{{- location -}}"
provider = "{{ provider }}"
account = ["DEV", "PROD", "INT"]
util = ["vault", "syslog"]
logging = true
auditing = true
description = "The subscription defines the cloud environment for the resident {{ origin_resource.name | capitalize }}."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"
